version: '3'
services:

  nginx:
    image: "bentein/quiz-nginx:ssl"
    depends_on:
      - quiz-app
      - quiz-auth
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:8080"
      - "443:443"

  database:
    image: "bentein/quiz-mysql:0.2"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass

  quiz-app:
    image: "bentein/quiz-app:0.1"
    depends_on:
      - database
    ports:
      - "40001:8080"
    env_file:
      - common.env

  quiz-auth:
    image: "bentein/quiz-auth:0.1"
    depends_on:
      - database
    ports:
      - "40000:8080"
    env_file:
      - common.env
      - authorization.env
  
  prometheus:
    image: "bentein/quiz-prometheus:0.2"
    depends_on:
      - quiz-app
      - quiz-auth
    ports:
      - "9090:9090"
  
  grafana:
    image: "bentein/quiz-grafana:0.2"
    ports:
      - "3001:3000"
  
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
