global:
  scrape_interval:     5s
  evaluation_interval: 5s
  
scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['quiz-app:8080']