{
 "title": "Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Users",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{method=\"POST\",status=\"201\",uri=\"/identity\"}\t"
    }
   ]
  },
  {
   "title": "Attempts",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{uri=\"/registration\",method=\"POST\",status=\"201\"}"
    }
   ]
  },
  {
   "title": "Answers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{uri=\"/response\", method=\"POST\", status=\"201\"}"
    }
   ]
  },
  {
   "title": "Registed users",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{uri=~\"/contactinfo*.\",method=\"POST\",status=\"201\"}) - \nsum(http_server_requests_seconds_count{uri=~\"/contactinfo/{identityId}*.\",method=\"DELETE\",status=\"204\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "format": "dthms",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{instance=\"identity-service:8080\"}"
    }
   ]
  },
  {
   "title": "Up since",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "format": "dateTimeAsUS",
   "valueName": "avg",
   "targets": [
    {
     "expr": "1000 * \nprocess_start_time_seconds{instance=\"identity-service:8080\"}"
    }
   ]
  },
  {
   "title": "Used memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"identity-service:8080\", area=\"heap\"})",
     "legendFormat": "identity-service"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"question-service:8080\", area=\"heap\"})",
     "legendFormat": "question-service"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"response-service:8080\", area=\"heap\"})",
     "legendFormat": "response-serivce"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{instance=\"score-service:8080\", area=\"heap\"})",
     "legendFormat": "score-service"
    }
   ]
  }
 ]
}